# Generated by Django 3.0.9 on 2020-08-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('year_published', models.IntegerField()),
                ('librarian', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Librarian')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Library')),
            ],
        ),
    ]
